### ISSUE TITLE
when i am trying the salesforce dataloader summons from Command prompt in salesforce

### ISSUE THREAD

**Issue by Anilchundu** [forcedotcom/wsc#106]
0 [main] INFO com.salesforce.lexiloader.process.ProcessConfig  - Loading process configuration from config file: c:\salesforce\conf\process-conf.xml
78 [main] INFO org.springframework.beans.factory.xml.XmlBeanDefinitionReader  - Loading XML bean definitions from file [c:\salesforce\conf\process-conf.xml]
81 [main] DEBUG org.springframework.beans.factory.xml.XmlBeanDefinitionReader  - Using JAXP implementation [com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl@1256ea2]
129 [main] DEBUG org.springframework.beans.factory.xml.ResourceEntityResolver  - Trying to resolve XML entity with public ID [-//SPRING//DTD BEAN//EN] and system ID [http://www.springframework.org/dtd/spring-beans.dtd]
130 [main] DEBUG org.springframework.beans.factory.xml.ResourceEntityResolver  - Trying to locate [spring-beans.dtd] in Spring jar
132 [main] DEBUG org.springframework.beans.factory.xml.ResourceEntityResolver  - Found beans DTD [http://www.springframework.org/dtd/spring-beans.dtd] in classpath
221 [main] DEBUG org.springframework.beans.factory.xml.DefaultXmlBeanDefinitionParser  - Loading bean definitions
227 [main] DEBUG org.springframework.beans.factory.xml.DefaultXmlBeanDefinitionParser  - Default lazy init 'false'
227 [main] DEBUG org.springframework.beans.factory.xml.DefaultXmlBeanDefinitionParser  - Default autowire 'no'
227 [main] DEBUG org.springframework.beans.factory.xml.DefaultXmlBeanDefinitionParser  - Default dependency check 'none'
234 [main] INFO org.springframework.core.CollectionFactory  - JDK 1.4+ collections available
243 [main] INFO org.springframework.core.CollectionFactory  - Commons Collections 3.x available
250 [main] DEBUG org.springframework.core.CollectionFactory  - Creating [java.util.LinkedHashMap]
260 [main] DEBUG org.springframework.core.CollectionFactory  - Creating [java.util.LinkedHashMap]
262 [main] DEBUG org.springframework.core.CollectionFactory  - Creating [java.util.LinkedHashMap]
264 [main] DEBUG org.springframework.core.CollectionFactory  - Creating [java.util.LinkedHashMap]
267 [main] DEBUG org.springframework.core.CollectionFactory  - Creating [java.util.LinkedHashMap]
268 [main] DEBUG org.springframework.core.CollectionFactory  - Creating [java.util.LinkedHashMap]
270 [main] DEBUG org.springframework.core.CollectionFactory  - Creating [java.util.LinkedHashMap]
272 [main] DEBUG org.springframework.core.CollectionFactory  - Creating [java.util.LinkedHashMap]
275 [main] DEBUG org.springframework.core.CollectionFactory  - Creating [java.util.LinkedHashMap]
277 [main] DEBUG org.springframework.core.CollectionFactory  - Creating [java.util.LinkedHashMap]
278 [main] DEBUG org.springframework.core.CollectionFactory  - Creating [java.util.LinkedHashMap]
281 [main] DEBUG org.springframework.core.CollectionFactory  - Creating [java.util.LinkedHashMap]
284 [main] DEBUG org.springframework.core.CollectionFactory  - Creating [java.util.LinkedHashMap]
284 [main] DEBUG org.springframework.beans.factory.xml.DefaultXmlBeanDefinitionParser  - Found 13 <bean> elements in file [c:\salesforce\conf\process-conf.xml]
286 [main] DEBUG org.springframework.beans.factory.xml.XmlBeanFactory  - Creating instance of bean 'sf_export_contact' with merged definition [Root bean: class [com.salesforce.lexiloader.process.ProcessRunner]; abstract=false; singleton=false; lazyInit=false; autowire=0; dependencyCheck=0; initMethodName=null; destroyMethodName=null; factoryMethodName=null; factoryBeanName=null; defined in file [c:\salesforce\conf\process-conf.xml]]
286 [main] DEBUG org.springframework.beans.factory.xml.XmlBeanFactory  - Invoking BeanPostProcessors before instantiation of bean 'sf_export_contact'
314 [main] DEBUG org.springframework.beans.CachedIntrospectionResults  - Getting BeanInfo for class [com.salesforce.lexiloader.process.ProcessRunner]
324 [main] DEBUG org.springframework.beans.CachedIntrospectionResults  - Caching PropertyDescriptors for class [com.salesforce.lexiloader.process.ProcessRunner]
324 [main] DEBUG org.springframework.beans.CachedIntrospectionResults  - Found property 'class' of type [java.lang.Class]
325 [main] DEBUG org.springframework.beans.CachedIntrospectionResults  - Found property 'configOverrideMap' of type [java.util.Map]
325 [main] DEBUG org.springframework.beans.CachedIntrospectionResults  - Found property 'controller' of type [com.salesforce.lexiloader.controller.Controller]
325 [main] DEBUG org.springframework.beans.CachedIntrospectionResults  - Found property 'name' of type [java.lang.String]
325 [main] DEBUG org.springframework.beans.CachedIntrospectionResults  - Class [com.salesforce.lexiloader.process.ProcessRunner] is cache-safe
332 [main] DEBUG org.springframework.core.CollectionFactory  - Creating [java.util.LinkedHashMap]
333 [main] DEBUG org.springframework.beans.BeanWrapperImpl  - About to invoke write method [public void com.salesforce.lexiloader.process.ProcessRunner.setName(java.lang.String)] on object of class [com.salesforce.lexiloader.process.ProcessRunner]
333 [main] DEBUG org.springframework.beans.BeanWrapperImpl  - Invoked write method [public void com.salesforce.lexiloader.process.ProcessRunner.setName(java.lang.String)] with value of type [java.lang.String]
333 [main] DEBUG org.springframework.beans.BeanWrapperImpl  - About to invoke write method [public void com.salesforce.lexiloader.process.ProcessRunner.setConfigOverrideMap(java.util.Map)] on object of class [com.salesforce.lexiloader.process.ProcessRunner]
333 [main] DEBUG org.springframework.beans.BeanWrapperImpl  - Invoked write method [public void com.salesforce.lexiloader.process.ProcessRunner.setConfigOverrideMap(java.util.Map)] with value of type [java.util.Map]
334 [main] DEBUG org.springframework.beans.factory.xml.XmlBeanFactory  - Invoking BeanPostProcessors before initialization of bean 'sf_export_contact'
334 [main] DEBUG org.springframework.beans.factory.xml.XmlBeanFactory  - Invoking afterPropertiesSet() on bean with name 'sf_export_contact'
334 [main] DEBUG org.springframework.beans.factory.xml.XmlBeanFactory  - Invoking BeanPostProcessors after initialization of bean 'sf_export_contact'
374 [sf_export_contact] INFO com.salesforce.lexiloader.controller.Controller  - The controller config has been initialized
385 [sf_export_contact] INFO com.salesforce.lexiloader.process.ProcessRunner  - Initializing process engine
385 [sf_export_contact] INFO com.salesforce.lexiloader.process.ProcessRunner  - Loading parameters
1594 [sf_export_contact] INFO com.salesforce.lexiloader.config.LastRun  - Last run info will be saved in file: c:\salesforce\conf\sf_export_contact_lastRun.properties
1595 [sf_export_contact] INFO com.salesforce.lexiloader.process.ProcessRunner  - Logging in to: https://www.salesforce.com
1607 [sf_export_contact] INFO com.salesforce.lexiloader.client.PartnerClient  - Beginning Partner Salesforce login ....
1631 [sf_export_contact] INFO com.salesforce.lexiloader.client.PartnerClient  - Salesforce login to https://www.salesforce.com/services/Soap/u/16.0 as user activebatch@cambridge.org
2526 [sf_export_contact] INFO com.salesforce.lexiloader.dao.DataAccessObjectFactory  - Instantiating data access object: \NAS-EAST\abat_prod_dbteam\data\sf\sf2local\sf_contact.csv of type: csvWrite
2527 [sf_export_contact] INFO com.salesforce.lexiloader.process.ProcessRunner  - Checking the data access object connection
2544 [sf_export_contact] INFO com.salesforce.lexiloader.process.ProcessRunner  - Setting field types
2824 [sf_export_contact] ERROR com.salesforce.lexiloader.client.PartnerClient  - Error while calling web service operation: describeSObject, error was: Failed to send request to https://emea.salesforce.com/services/Soap/u/16.0/00D200000007KUV
com.sforce.ws.ConnectionException: Failed to send request to https://emea.salesforce.com/services/Soap/u/16.0/00D200000007KUV
    at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:95)
    at com.sforce.soap.partner.PartnerConnection.describeSObject(PartnerConnection.java:1134)
    at com.salesforce.lexiloader.client.PartnerClient.describeSObject(PartnerClient.java:543)
    at com.salesforce.lexiloader.client.PartnerClient.setFieldTypes(PartnerClient.java:346)
    at com.salesforce.lexiloader.controller.Controller.setFieldTypes(Controller.java:131)
    at com.salesforce.lexiloader.process.ProcessRunner.run(ProcessRunner.java:125)
    at com.salesforce.lexiloader.process.ProcessRunner.main(ProcessRunner.java:228)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at com.sun.net.ssl.internal.ssl.Alerts.getSSLException(Alerts.java:150)
    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1476)
    at com.sun.net.ssl.internal.ssl.Handshaker.fatalSE(Handshaker.java:174)
    at com.sun.net.ssl.internal.ssl.Handshaker.fatalSE(Handshaker.java:168)
    at com.sun.net.ssl.internal.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:847)
    at com.sun.net.ssl.internal.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:106)
    at com.sun.net.ssl.internal.ssl.Handshaker.processLoop(Handshaker.java:495)
    at com.sun.net.ssl.internal.ssl.Handshaker.process_record(Handshaker.java:433)
    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:815)
    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1025)
    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1038)
    at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:402)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:170)
    at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:836)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:230)
    at com.sforce.ws.transport.JdkHttpTransport.connect(JdkHttpTransport.java:115)
    at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:88)
    ... 6 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:221)
    at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:145)
    at sun.security.validator.Validator.validate(Validator.java:203)
    at com.sun.net.ssl.internal.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:172)
    at com.sun.net.ssl.internal.ssl.JsseX509TrustManager.checkServerTrusted(SSLContextImpl.java:320)
    at com.sun.net.ssl.internal.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:840)
    ... 18 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:236)
    at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:194)
    at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:216)
    ... 23 more
2827 [sf_export_contact] ERROR com.salesforce.lexiloader.process.ProcessRunner  - Failed to send request to https://emea.salesforce.com/services/Soap/u/16.0/00D200000007KUV
Exception in thread "main" java.lang.RuntimeException: com.sforce.ws.ConnectionException: Failed to send request to https://emea.salesforce.com/services/Soap/u/16.0/00D200000007KUV
    at com.salesforce.lexiloader.process.ProcessRunner.run(ProcessRunner.java:151)
    at com.salesforce.lexiloader.process.ProcessRunner.main(ProcessRunner.java:228)
Caused by: com.sforce.ws.ConnectionException: Failed to send request to https://emea.salesforce.com/services/Soap/u/16.0/00D200000007KUV
    at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:95)
    at com.sforce.soap.partner.PartnerConnection.describeSObject(PartnerConnection.java:1134)
    at com.salesforce.lexiloader.client.PartnerClient.describeSObject(PartnerClient.java:543)
    at com.salesforce.lexiloader.client.PartnerClient.setFieldTypes(PartnerClient.java:346)
    at com.salesforce.lexiloader.controller.Controller.setFieldTypes(Controller.java:131)
    at com.salesforce.lexiloader.process.ProcessRunner.run(ProcessRunner.java:125)
    ... 1 more
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at com.sun.net.ssl.internal.ssl.Alerts.getSSLException(Alerts.java:150)
    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1476)
    at com.sun.net.ssl.internal.ssl.Handshaker.fatalSE(Handshaker.java:174)
    at com.sun.net.ssl.internal.ssl.Handshaker.fatalSE(Handshaker.java:168)
    at com.sun.net.ssl.internal.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:847)
    at com.sun.net.ssl.internal.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:106)
    at com.sun.net.ssl.internal.ssl.Handshaker.processLoop(Handshaker.java:495)
    at com.sun.net.ssl.internal.ssl.Handshaker.process_record(Handshaker.java:433)
    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:815)
    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1025)
    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1038)
    at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:402)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:170)
    at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:836)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:230)
    at com.sforce.ws.transport.JdkHttpTransport.connect(JdkHttpTransport.java:115)
    at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:88)
    ... 6 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:221)
    at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:145)
    at sun.security.validator.Validator.validate(Validator.java:203)
    at com.sun.net.ssl.internal.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:172)
    at com.sun.net.ssl.internal.ssl.JsseX509TrustManager.checkServerTrusted(SSLContextImpl.java:320)
    at com.sun.net.ssl.internal.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:840)
    ... 18 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:236)
    at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:194)
    at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:216)
    ... 23 more
ExitCode 1

---
-         J O B     S T A T I S T I C S            *
-                                                  *
-          ActiveBatch (r) Version 8               *
-     The Enterprise Job Scheduling System         *
-                Engineered By                     *
-       Advanced Systems Concepts Inc              *
-          http://www.advsyscon.com                *
  ****************************************************

Job Id               : 7347149
Job Name             : ExpSfContact
Batch Id             : 7347146
Command Line         : c:\salesforce\bin\process.bat sf_export_contact
Working Directory    : 
Client Machine       : IT65
Submitted by         : CAMBRIDGE\rcpn
Job Start Time       : 14/08/2015 08:29:56

Execution User       : CAMBRIDGE\abatqueue
Execution Queue      : LocalAbatQueue
Execution Machine    : ABAT02
Job Scheduler        : ABAT02
Job Completed at     : 14/08/2015 08:29:59

Elapsed Time         :      0 00:00:03.348
CPU Time             :      0 00:00:00.046
Completion Status    : -805502974 (0xcffd0002)
                     : (%ABAT-E-FAILURE, Failure in requested operation)

-------------Job Object Statistics--------------
Total User Time      :      0 00:00:01.747
Total Kernel Time    :      0 00:00:00.546
Page Faults          : 8221
Process Count        : 2
Peak Process Memory  : 21925888
Peak Job Memory      : 24174592
Read Operations      : 26101
Read Byte Count      : 16395249
Write Operations     : 143
Write Byte Count     : 15391
Other I/O Operations : 1054
Other I/O Byte Count : 222257

---

  Note: except where specifically noted, all times  
        are based on the Execution Agent Machine.  
********************_End of Log**_******************

**Comment by reubencornel** [comment]
This needs to be looked at by dataloader. Not sure if we can do anything about this.

**Comment by Landowy** [comment]
Hi,

I had the same.

Completion Status : -805502974 is agent service issue - changed IP to failover agent and it worked, after primary agent restart issue gone
