### ISSUE TITLE
com.force.api:force-partner-api: wrong default auth endpoint since 34.0.0

### ISSUE THREAD

**Issue by rgbj** [forcedotcom/wsc#110]
Using [com.force.api:force-partner-api:33.0.3](http://search.maven.org/#artifactdetails%7Ccom.force.api%7Cforce-partner-api%7C33.0.3%7Cjar), this code:

```java
ConnectorConfig config = new ConnectorConfig();
config.setUsername(username);
config.setPassword(password + security_token);
PartnerConnection connection = Connector.newConnection(config);
System.out.println("auth endpoint: " + config.getAuthEndpoint());
```
outputs: `auth endpoint: https://login.salesforce.com/services/Soap/u/33.0`

Using [com.force.api:force-partner-api:34.0.0](http://search.maven.org/#artifactdetails%7Ccom.force.api%7Cforce-partner-api%7C34.0.0%7Cjar), the same code fails with:

```
com.sforce.ws.ConnectionException: Failed to send request to https://login-blaze1.soma.salesforce.com/services/Soap/u/34.0
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1147)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:998)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1282)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1257)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
	at com.sforce.ws.transport.JdkHttpTransport.connectRaw(JdkHttpTransport.java:136)
	at com.sforce.ws.transport.JdkHttpTransport.connectLocal(JdkHttpTransport.java:100)
	at com.sforce.ws.transport.JdkHttpTransport.connectLocal(JdkHttpTransport.java:95)
	at com.sforce.ws.transport.JdkHttpTransport.connect(JdkHttpTransport.java:91)
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:95)
	at com.sforce.soap.partner.PartnerConnection.login(PartnerConnection.java:1402)
	at com.sforce.soap.partner.PartnerConnection.<init>(PartnerConnection.java:426)
	at com.sforce.soap.partner.Connector.newConnection(Connector.java:27)
```

indeed,

```
$ host login.salesforce.com            
login.salesforce.com is an alias for login2.l.salesforce.com.
login2.l.salesforce.com is an alias for login-was.g.salesforce.com.
login-was.g.salesforce.com has address 96.43.148.27
login-was.g.salesforce.com has address 96.43.149.27
login-was.g.salesforce.com has address 96.43.150.124
login-was.g.salesforce.com has address 96.43.150.251
$ host login-blaze1.soma.salesforce.com
Host login-blaze1.soma.salesforce.com not found: 3(NXDOMAIN)
$ 
```

workaround:

```java
ConnectorConfig config = new ConnectorConfig();
config.setAuthEndpoint("https://login.salesforce.com/services/Soap/u/34.0");
config.setUsername(username);
config.setPassword(password + security_token);
PartnerConnection connection = Connector.newConnection(config);
```

It seems to me that either the default endpoint should be corrected, or the auth endpoint should be required.

**Comment by gnguyen-sfdc** [comment]
Sorry it took so long, but we've uploaded version 35.0.1 of the jar which has the correct default endpoint. Thank you for bringing it to our attention.
