### ISSUE TITLE
NoClassDefFoundError requiring "org/codehaus/jackson/ObjectCodec"

### ISSUE THREAD

**Issue by sudharsannr** [forcedotcom/wsc#138]
I ran into an issue when building with the latest wsc. All generation seems to be fine but throws a runtime error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/codehaus/jackson/ObjectCodec
    at common.ConnectionManager.createBulkConnection(ConnectionManager.java:72)
    at common.ConnectionManager.getBulkConnection(ConnectionManager.java:115)
    at salesforce.SalesforceConnector.<init>(SalesforceConnector.java:144)
    at test.SalesforceTest.parseAndRun(SalesforceTest.java:221)
    at test.SalesforceTest.main(SalesforceTest.java:98)
Caused by: java.lang.ClassNotFoundException: org.codehaus.jackson.ObjectCodec
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 5 more
```

This is due to the fact of the [referenced json libraries in BulkConnector](https://github.com/forcedotcom/wsc/blob/bd5c0c1c03c5f26f32d35a1febe16979c797b1a4/src/main/java/com/sforce/async/BulkConnection.java#L58):

```
import org.codehaus.jackson.JsonFactory;
import org.codehaus.jackson.JsonGenerator;
import org.codehaus.jackson.JsonParser;
import org.codehaus.jackson.map.DeserializationConfig.Feature;
import org.codehaus.jackson.map.ObjectMapper;
```

This would require the [dependency](http://mvnrepository.com/artifact/org.codehaus.jackson/jackson-mapper-asl/1.9.13). Could we move this to the [newer depency](http://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind)

**Comment by jziesing** [comment]
I am running into the same issue running the Force Wsc library in a java application.  The application compiles without errors to mis-referenced classes, but when it runs it throws an error creating a new BulkConnection.  The issue is with v37.0.3.  The error is: Exception in thread “main” java.lang.NoClassDefFoundError: org/codehaus/jackson/OjectCodec
The resource throwing the error is com.sforce.async.BulkConnection.class.  I am wondering if anyone has any insight on this?  Have there been any recent changes to this library that could throw this error, or cause the connection to be depreciated?

**Comment by mgrumbach** [comment]
As of WSC 49.2.0, WSC has been migrated to depend on Jackson 2.10.3. So there is no longer any dependence on Jackson 1.9.13.
