### ISSUE TITLE
Unable to retrieve bulk job status in JSON

### ISSUE THREAD

**Issue by sudharsannr** [forcedotcom/wsc#139]
Hi,

I am trying to submit bulk job query in JSON format. When I try to check the job status, I receive the following error:
```
com.sforce.async.AsyncApiException: ClientInputError : Failed to parse batch info 
	at com.sforce.async.BulkConnection.getBatchInfo(BulkConnection.java:573) ~[force-wsc-37.0.3.jar:?]
	at com.sforce.async.BulkConnection.getBatchInfo(BulkConnection.java:550) ~[force-wsc-37.0.3.jar:?]
	at salesforce.BulkJobManager.monitorJobs(BulkJobManager.java:162) [classes/:?]	
Caused by: com.sforce.ws.ConnectionException: Failed to get next element
	at com.sforce.ws.parser.XmlInputStream.nextTag(XmlInputStream.java:169) ~[force-wsc-37.0.3.jar:?]
	at com.sforce.ws.bind.TypeMapper.consumeStartTag(TypeMapper.java:436) ~[force-wsc-37.0.3.jar:?]
	at com.sforce.async.BatchInfo.load(BatchInfo.java:308) ~[force-wsc-37.0.3.jar:?]
	at com.sforce.async.BulkConnection.getBatchInfo(BulkConnection.java:565) ~[force-wsc-37.0.3.jar:?]
	... 10 more
Caused by: com.sforce.ws.parser.XmlPullParserException: only whitespace content allowed before start tag and not { (position: START_DOCUMENT seen {... @1:1) 
	at com.sforce.ws.parser.MXParser.parseProlog(MXParser.java:1532) ~[force-wsc-37.0.3.jar:?]
	at com.sforce.ws.parser.MXParser.nextImpl(MXParser.java:1408) ~[force-wsc-37.0.3.jar:?]
	at com.sforce.ws.parser.MXParser.next(MXParser.java:1111) ~[force-wsc-37.0.3.jar:?]
	at com.sforce.ws.parser.MXParser.nextTag(MXParser.java:1096) ~[force-wsc-37.0.3.jar:?]
	at com.sforce.ws.parser.XmlInputStream.nextTag(XmlInputStream.java:167) ~[force-wsc-37.0.3.jar:?]
	at com.sforce.ws.bind.TypeMapper.consumeStartTag(TypeMapper.java:436) ~[force-wsc-37.0.3.jar:?]
	at com.sforce.async.BatchInfo.load(BatchInfo.java:308) ~[force-wsc-37.0.3.jar:?]
	at com.sforce.async.BulkConnection.getBatchInfo(BulkConnection.java:565) ~[force-wsc-37.0.3.jar:?]
	... 10 more
```

However, when I try to submit the job where the _ContentType is CSV_, it works fine. Is this due to the change in request/response format in submitting the bulk jobs?

**Comment by amihaihalevy** [comment]
Hi,
Looking into the stack trace it seems that XML parser is trying to parse the JSON file which cause the exception.
If you want to use JSON format you need to make sure that you use it all the way. While creating the job, set the content type to be JSON. Once set and job is created, you should use JSON format only, from now on.
If your job's content type is set to XML, you can submit calls only with XML format.
CSV is working fine, since it is set to work with XML content type (which your job content type is probably is set to).

**Comment by sudharsannr** [comment]
Got it. 
I was using
```
BatchInfo updbatchInfo = ConnectionManager.getBulkConnection().getBatchInfo(jobId,
								batchInfo.getId());
```
where the default mode is using XML.

However, I am supposed to use
`ConnectionManager.getBulkConnection().getBatchInfo(jobId, batchInfo.getId(), respFormat);`
