### ISSUE TITLE
Unmarshalling PicklistValue object fails: unable to find end tag at:  START_TAG seen ...<default>false</default><cssExposed>

### ISSUE THREAD

**Issue by jtomtran** [forcedotcom/wsc#140]
WSDL: 36.0
Metadata connection version: 36.0

The org is on Summer 16. The problem is that Summer 16 org metadata response alters the order of fields under PicklistValue (swapping cssExposed & default), even though we are setting connection version at 36.0.

Any suggestion guys ? Is there any way we can get WSC to work in a order in-sensitive fashion ? seems really fragile. 

Caused by: com.sforce.ws.ConnectionException: unable to find end tag at:  START_TAG seen ...<default>false</default><cssExposed>... @1:439
	at com.sforce.ws.bind.TypeMapper.consumeEndTag(TypeMapper.java:443) ~[force-wsc-36.3.0.jar:na]
	at com.sforce.soap.metadata.PicklistValue.load(PicklistValue.java:474) ~[metadata_v36.jar:na]
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:688) ~[force-wsc-36.3.0.jar:na]
	at com.sforce.ws.bind.TypeMapper.readArray(TypeMapper.java:586) ~[force-wsc-36.3.0.jar:na]
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:564) ~[force-wsc-36.3.0.jar:na]

**Comment by inakirzabalegui** [comment]
Same problem although my org is not in Summer, still Spring
