### ISSUE TITLE
TLS error using com.sforce.ws.transport.GaeHttpTransport

### ISSUE THREAD

**Issue by zandrade** [forcedotcom/wsc#143]
Using WSC in app engine is generating the following error:

Exception in thread "main" [UnexpectedErrorFault [ApiFault  exceptionCode='UNSUPPORTED_CLIENT'
 exceptionMessage='TLS 1.0 has been disabled in this organization. Please use TLS 1.1 or higher when connecting to Salesforce using https.'
 extendedErrorDetails='{[0]}'
]
]

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:383)
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:687)
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:562)
	at com.sforce.ws.transport.SoapConnection.parseDetail(SoapConnection.java:236)
	at com.sforce.ws.transport.SoapConnection.createException(SoapConnection.java:210)
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:156)
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:99)
	at com.sforce.soap.enterprise.EnterpriseConnection.login(EnterpriseConnection.java:1115)
	at com.sforce.soap.enterprise.EnterpriseConnection.<init>(EnterpriseConnection.java:386)
	at com.sforce.soap.enterprise.Connector.newConnection(Connector.java:27)

**Comment by zandrade** [comment]
Not reproducible outside of dev server

**Comment by unhillbilly** [comment]
I believe this will be an issue for new customers in production environment. 
See
https://help.salesforce.com/apex/HTViewSolution?id=000221207#Whendisable
