### ISSUE TITLE
project build failed

### ISSUE THREAD

**Issue by iviraj90** [forcedotcom/wsc#151]
Tests run: 26, Failures: 7, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.262 s
[INFO] Finished at: 2016-07-19T22:30:21+05:30
[INFO] Final Memory: 26M/238M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.7.1:test (default-test) on project force-wsc: There are test failures.
[ERROR] 
[ERROR] Please refer to C:\Users\abc\Downloads\wsc-master\wsc-master\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.7.1:test (default-test) on project force-wsc: There are test failures.

Please refer to C:\Users\abc\Downloads\wsc-master\wsc-master\target\surefire-reports for the individual test results.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to C:\Users\abc\Downloads\wsc-master\wsc-master\target\surefire-reports for the individual test results.
    at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution(SurefireHelper.java:74)
    at org.apache.maven.plugin.surefire.SurefirePlugin.execute(SurefirePlugin.java:631)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    ... 20 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by csouchet** [comment]
Hi !!

I have exactly the same problem.
I try to compile the following branches with JDK 7 & 8 and Maven 3.3.9: 37.0.1, 37.0.3, 38.0.0.

The tests in error on the 37.0.3 branch: 
- [com.sforce.ws.codegen.AggregateCodeGeneratorTest.txt](https://github.com/forcedotcom/wsc/files/422162/com.sforce.ws.codegen.AggregateCodeGeneratorTest.txt)
- [com.sforce.ws.codegen.ComplexTypeCodeGeneratorTest.txt](https://github.com/forcedotcom/wsc/files/422199/com.sforce.ws.codegen.ComplexTypeCodeGeneratorTest.txt)
- [com.sforce.ws.codegen.ConnectionCodeGeneratorTest.txt](https://github.com/forcedotcom/wsc/files/422201/com.sforce.ws.codegen.ConnectionCodeGeneratorTest.txt)
- [com.sforce.ws.codegen.ConnectorCodeGeneratorTest.txt](https://github.com/forcedotcom/wsc/files/422202/com.sforce.ws.codegen.ConnectorCodeGeneratorTest.txt)
- [com.sforce.ws.codegen.SObjectCodeGeneratorTest.txt](https://github.com/forcedotcom/wsc/files/422204/com.sforce.ws.codegen.SObjectCodeGeneratorTest.txt)
- [com.sforce.ws.codegen.SimpleTypeCodeGeneratorTest.txt](https://github.com/forcedotcom/wsc/files/422203/com.sforce.ws.codegen.SimpleTypeCodeGeneratorTest.txt)

**Comment by clvinning** [comment]
Same as the two above. Don't you just love it when proper, intuitive configuration isn't specified?

**Comment by IgorSmilkov** [comment]
Try to execute following command:
mvn clean package -DskipTests -Dgpg.skip

it works for me

**Comment by easycheese** [comment]
Thanks @IgorSmilkov that worked for me as well.

**Comment by reubencornel** [comment]
Closing because this issue is not visible in the latest version
