### ISSUE TITLE
force-wsc-40.1.1-uber.jar is not generated due to some Build error

### ISSUE THREAD

**Issue by patrosantosh** [forcedotcom/wsc#200]
Steps are  : 
1. Downloaded the repository as ZIP 
2. Executed the following command   :  "  mvn clean package  "
got the error 
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.7.1:test (default-test) on project force-wsc: There are test failures.

It doesnot generate force-wsc-40.1.1-uber.jar file which is needed to Integrate java Force.com
![2017-06-08 15_07_19-greenshot](https://user-images.githubusercontent.com/26456155/26922372-97df6726-4c5c-11e7-9f77-3a9e088b640d.png)

**Comment by reubencornel** [comment]
I tried doing a clean and package. I don't see any test failures. Which tests are failing for you? Please could you put the stack trace here.

**Comment by BartoszJanikGFT** [comment]
\AppData\Local\Temp\VoidReturnTest610658076249686004\com\sforce\soap\docSample\SoapConnection.java: The process cannot access the file because it is being used by another process.

**Comment by jjurisch** [comment]
I also get an error - I was able to bypass it using: `mvn clean package -Dgpg.skip -Dmaven.test.failure.ignore=true` but not sure if it succeeds as I'm stuck at the next step (which may be unrelated). 

Running 'cmd' as Administrator and with the -e flag outputs: 
![image](https://user-images.githubusercontent.com/492128/27704345-f69fcb6a-5ccf-11e7-85f9-690644fbc60b.png)

![image](https://user-images.githubusercontent.com/492128/27704372-157737d0-5cd0-11e7-8a6b-f30cc5a3a753.png)

Full trace within com.sforce.ws.codegen.VoidReturnTest.txt results in: 
```
-------------------------------------------------------------------------------
Test set: com.sforce.ws.codegen.VoidReturnTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.558 sec <<< FAILURE!
testVoidReturnValue(com.sforce.ws.codegen.VoidReturnTest)  Time elapsed: 3.458 sec  <<< ERROR!
java.nio.file.FileSystemException: C:\Users\A1RQLZZ\AppData\Local\Temp\VoidReturnTest1225436231312245312\com\sforce\soap\docSample\SoapConnection.java: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1126)
	at com.sforce.ws.codegen.CodeGeneratorTestUtil$1.visitFile(CodeGeneratorTestUtil.java:94)
	at com.sforce.ws.codegen.CodeGeneratorTestUtil$1.visitFile(CodeGeneratorTestUtil.java:90)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.sforce.ws.codegen.CodeGeneratorTestUtil.cleanupDirectory(CodeGeneratorTestUtil.java:90)
	at com.sforce.ws.codegen.VoidReturnTest.tearDown(VoidReturnTest.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:37)
	at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:35)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:146)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:145)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:70)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)

```

**Comment by jjurisch** [comment]
I was able to switch to a different version to work around this. It packages 39.0.0 correctly with no unit test errors, but 39.0.2 threw the error. I didn't try 39.0.1 but can if that would help debug. 

```
git checkout e8f1273f4722d4073012349e144d0ea6bcddb564
mvn clean package -Dgpg.skip
```

**Comment by dgwgbh** [comment]
I am having the same issue but was able to use the workaround posted above (thank you!) to get by it.
