### ISSUE TITLE
SoapConnection.send throws UnexpectedErrorFault when querying Contact Id by Email

### ISSUE THREAD

**Issue by KoichiSenada** [forcedotcom/wsc#203]
**com.force.api:force-wsc:40.0.0**

Contact query:
```
SELECT Id FROM Contact WHERE Email='user@example.com'
```

In some cases it throws **UnexpectedErrorFault**

```
com.sforce.soap.enterprise.fault.UnexpectedErrorFault: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:673)
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:556)
	at com.sforce.ws.transport.SoapConnection.parseDetail(SoapConnection.java:236)
	at com.sforce.ws.transport.SoapConnection.createException(SoapConnection.java:210)
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:156)
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:99)
	at com.sforce.soap.enterprise.EnterpriseConnection.query(EnterpriseConnection.java:896)
```

Method `SoapConnection.send()` calls method `SoapConnection.receive()` with specifying the `Transport` parameter which returns `Transport.isSuccessful()` as `false`,  so then it calls `SoapConnection.createException()` which ends up with `UnexpectedErrorFault` for some reason.

Please fix it.

**Comment by elena-posea** [comment]
I have the same problem. Do you have any updates on this?

**Comment by Stephan202** [comment]
We hit the same issue with version 44.0.0. It appears that the Java client fails to handle an error message returned by the server, thereby obscuring said error. After attaching a debugger and setting a breakpoint at a suitable location I saw the server's error message:
> `UNSUPPORTED_API_VERSION: Invalid Api version specified on URL`

It turned out that we were trying to use API 44.0 with an environment that didn't support it yet. Downgrading to version 43.0 made the problem go away.
