### ISSUE TITLE
TypeMapper throws error on generated stub

### ISSUE THREAD

**Issue by sanderploegsma** [forcedotcom/wsc#233]
While retrieving an object from our SalesForce Enterprise API this library throws the following error:

```
com.sforce.ws.ConnectionException: Incompatible type 'class com.sforce.soap.enterprise.sobject.TrainingSeries__c' specified as xsi:type. It must be a subclass of 'class com.sforce.soap.enterprise.sobject.SObject'
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:627)
	at com.sforce.ws.bind.TypeMapper.readArray(TypeMapper.java:580)
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:558)
	at com.sforce.soap.enterprise.RetrieveResponse_element.setResult(RetrieveResponse_element.java:46)
	at com.sforce.soap.enterprise.RetrieveResponse_element.loadFields1(RetrieveResponse_element.java:105)
	at com.sforce.soap.enterprise.RetrieveResponse_element.loadFields(RetrieveResponse_element.java:81)
	at com.sforce.soap.enterprise.RetrieveResponse_element.load(RetrieveResponse_element.java:75)
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:674)
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:556)
	at com.sforce.ws.transport.SoapConnection.bind(SoapConnection.java:180)
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:154)
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:99)
	at com.sforce.soap.enterprise.EnterpriseConnection.retrieve(EnterpriseConnection.java:682)
```

The `com.sforce.soap.enterprise.sobject.TrainingSeries__c` class has been generated from our WSDL and extends `com.sforce.soap.enterprise.sobject.SObject`, so I don't see why this error would occur.

**Comment by sanderploegsma** [comment]
After some more testing I still can't figure out why this is happening. I tried retrieving a single `Contact`, thinking it had to do with our custom objects, but the same problem occurs. 

I enabled tracing to see if the response contains something weird, but everything looks fine:

Code:
``` java
SObject result = connection.retrieve("ID, Name", "Contact", new String[]{"*omitted*"});
```

Request:
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" 
  xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <env:Header>
    <SessionHeader xmlns="urn:enterprise.soap.sforce.com">
      <sessionId>*omitted*</sessionId>
    </SessionHeader>
  </env:Header>
  <env:Body>
    <m:retrieve xmlns:m="urn:enterprise.soap.sforce.com" 
      xmlns:sobj="urn:sobject.enterprise.soap.sforce.com">
      <m:fieldList>ID, Name</m:fieldList>
      <m:sObjectType>Contact</m:sObjectType>
      <m:ids>*omitted*</m:ids>
    </m:retrieve>
  </env:Body>
</env:Envelope>
```

Response:
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" 
  xmlns="urn:enterprise.soap.sforce.com" 
  xmlns:sf="urn:sobject.enterprise.soap.sforce.com" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <soapenv:Header>
    <LimitInfoHeader>
      <limitInfo>
        <current>3568</current>
        <limit>33000</limit>
        <type>API REQUESTS</type>
      </limitInfo>
    </LimitInfoHeader>
  </soapenv:Header>
  <soapenv:Body>
    <retrieveResponse>
      <result xsi:type="sf:Contact">
        <sf:Id>*omitted*</sf:Id>
        <sf:Name>*omitted*</sf:Name>
      </result>
    </retrieveResponse>
  </soapenv:Body>
</soapenv:Envelope>
```

Stacktrace:
```
om.sforce.ws.ConnectionException: Incompatible type 'class com.sforce.soap.enterprise.sobject.Contact' specified as xsi:type. It must be a subclass of 'class com.sforce.soap.enterprise.sobject.SObject'
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:627)
	at com.sforce.ws.bind.TypeMapper.readArray(TypeMapper.java:580)
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:558)
	at com.sforce.soap.enterprise.RetrieveResponse_element.setResult(RetrieveResponse_element.java:46)
	at com.sforce.soap.enterprise.RetrieveResponse_element.loadFields1(RetrieveResponse_element.java:105)
	at com.sforce.soap.enterprise.RetrieveResponse_element.loadFields(RetrieveResponse_element.java:81)
	at com.sforce.soap.enterprise.RetrieveResponse_element.load(RetrieveResponse_element.java:75)
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:674)
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:556)
	at com.sforce.ws.transport.SoapConnection.bind(SoapConnection.java:180)
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:154)
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:99)
	at com.sforce.soap.enterprise.EnterpriseConnection.retrieve(EnterpriseConnection.java:682)
```
