### ISSUE TITLE
TypeMapper fails on unsorted input

### ISSUE THREAD

**Issue by kratoon3** [forcedotcom/wsc#244]
Hi,

I am manipulating DX source directly. Metadata loading (unmarshalling) from a file fails when the metadata has unsorted children.
 
Profile that fails:  
```
<?xml version="1.0" encoding="UTF-8"?>
<Profile xmlns="http://soap.sforce.com/2006/04/metadata">
    <classAccesses>
        <apexClass>Class</apexClass>
        <enabled>true</enabled>
    </classAccesses>
    <applicationVisibilities>
        <application>App</application>
        <default>false</default>
        <visible>true</visible>
    </applicationVisibilities>
</Profile>
```
Stack trace:
```
Exception in thread "main" com.sforce.ws.ConnectionException: unable to find end tag at:  START_TAG seen ...</classAccesses>\n    <applicationVisibilities>... @7:30
	at com.sforce.ws.bind.TypeMapper.consumeEndTag(TypeMapper.java:441)
	at com.sforce.soap.metadata.Profile.load(Profile.java:575)
	...
```

**Comment by abhinavChadda** [comment]
It is most likely happening due to the ordering of the elements in your request. can you please try again with <applicationVisibilities/> before < classAccesses/>
