### ISSUE TITLE
java.lang.ClassNotFoundException: org.apache.commons.beanutils.BeanIntrospector on version 47.0

### ISSUE THREAD

**Issue by Kamalkant83** [forcedotcom/wsc#271]
when I am trying to execute query using SOAP API on Account object with fields **billingstreet,billingcity,billingstate,billingpostalcode,billingcountry,billinglatitude,billinglongitude,billinggeocodeaccuracy,billingaddress,shippingstreet,shippingcity,shippingstate,shippingpostalcode,shippingcountry,shippinglatitude,shippinglongitude,shippinggeocodeaccuracy,shippingaddress** then I am getting below error 

java.lang.ClassNotFoundException: org.apache.commons.beanutils.BeanIntrospector
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1720)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1571)
	at com.sforce.ws.bind.XmlObject.extractChildElement(XmlObject.java:355)
	at com.sforce.ws.bind.XmlObject.loadAfterStartTag(XmlObject.java:311)
	at com.sforce.ws.bind.XmlObject.load(XmlObject.java:294)
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:678)
	at com.sforce.ws.bind.TypeMapper.readArray(TypeMapper.java:584)
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:562)
	at com.sforce.soap.partner.QueryResult.setRecords(QueryResult.java:115)
	at com.sforce.soap.partner.QueryResult.loadFields1(QueryResult.java:210)
	at com.sforce.soap.partner.QueryResult.loadFields(QueryResult.java:181)
	at com.sforce.soap.partner.QueryResult.load(QueryResult.java:175)
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:678)
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:560)
	at com.sforce.soap.partner.QueryResponse_element.setResult(QueryResponse_element.java:48)
	at com.sforce.soap.partner.QueryResponse_element.loadFields1(QueryResponse_element.java:107)
	at com.sforce.soap.partner.QueryResponse_element.loadFields(QueryResponse_element.java:83)
	at com.sforce.soap.partner.QueryResponse_element.load(QueryResponse_element.java:77)
	at com.sforce.ws.bind.TypeMapper.readSingle(TypeMapper.java:678)
	at com.sforce.ws.bind.TypeMapper.readObject(TypeMapper.java:560)
	at com.sforce.ws.transport.SoapConnection.bind(SoapConnection.java:194)
	at com.sforce.ws.transport.SoapConnection.receive(SoapConnection.java:161)
	at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:108)
	at com.sforce.soap.partner.PartnerConnection.query(PartnerConnection.java:575)

Is there any solution or patch for this ??
FYI same issue was logged in dataloader  https://trailblazer.salesforce.com/issues_view?id=a1p3A000001YmNXQA0&title=data-loader-v46-exporting-address-fields-generates-org-apache-commons-beanutils-beanintrospector-error

Thanks
Kamal

**Comment by emmandezLC** [comment]
I had a similar issue but removed the BillingAddress field and got my code to run
