### ISSUE TITLE
Getting NoSuchMethodError on new EnterpriseConnection

### ISSUE THREAD

**Issue by darshanNTNX** [forcedotcom/wsc#306]
```
Caused by: java.lang.NoSuchMethodError: com.sforce.ws.bind.TypeMapper.<init>(Ljava/lang/String;Ljava/lang/String;Z)V
	at com.sforce.soap.enterprise.EnterpriseConnection.<init>(EnterpriseConnection.java:18)
	at xxx.initialize(xxx.java:138)
```

Getting the above mentioned error on using enterprise and enterprise-partner JARs created using : 
`target/force-wsc-56.0.0-uber.jar`

On Decompiling : 
**EnterpriseConnection** class (<enterprise_jar>/com/sforce/soap/enterprise/EnterpriseConnection.class) has field : 
`private TypeMapper __typeMapper = new TypeMapper((String)null, (String)null, false);` 

Whereas the **TypeMapper** constructor doesnt expect any arguments (.m2/repository/com/force/api/force-wsc/34.2.2/force-wsc-34.2.2.jar!/com/sforce/ws/bind/TypeMapper.class)

Kindly Assist !

**Comment by krissirk** [comment]
Looks like you're using WSC 56.0.0 to generate a client, but when running the client, you're are using WSC 34.2.2 (which doesn't have the new constructor for TypeMapper). If you continue to run into trouble, please open a support case.
